- hosts: all
  remote_user: docker
  become: yes

  tasks:
    - name: Check if directory /tmp exists
      file:
        path: /tmp
        state: directory
        mode: '0755'

    - name: Copy a script to all slaves
      copy:
        src: ./automation/script.sh
        dest: /tmp/hello.sh
        mode: '0755'

    - name: Run the script on a remote host
      shell: /tmp/hello.sh

